### PR TITLE
Getting things ready for an initial release.  This gets rid of all th…

### PR DESCRIPTION
**Pull request by mikesamuel**
…e ad-hoc parsing in favor of a single event-based parser.  We now properly handle case insensitivity (caveat u flag).  It fleshes out test cases and documentation.

### CODE REVIEW

**Comment by mikesamuel** [comment]
The table was a little borken so I tweaked it.  https://github.com/mikesamuel/regexp-make-js/blob/release-candidate/README.md should let you see the current state of the docs.

**Comment by erights** [comment]
Github says "This branch has conflicts that must be resolved" and greys out my "Merge pull request" button.

**Comment by erights** [comment]
Github says "This branch has conflicts that must be resolved" and greys out
my "Merge pull request" button.

On Sat, Aug 8, 2015 at 7:47 AM, Mike Samuel notifications@github.com
wrote:

> The table was a little borken so I tweaked it.
> https://github.com/mikesamuel/regexp-make-js/blob/release-candidate/README.md
> should let you see the current state of the docs.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mikesamuel/regexp-make-js/pull/8#issuecomment-128987916
> .

## 

Text by me above is hereby placed in the public domain

  Cheers,
  --MarkM

**Comment by mikesamuel** [comment]
I think it's mergeable now.

**Pull request merged**
